version: "3"

services:
  mariadb:
    image: mariadb:10.1.11
    volumes:
      - "./mariadb:/var/lib/mysql"
    environment:
     - MYSQL_DATABASE=fredbetdb
     - MYSQL_ROOT_PASSWORD=secred
     - MYSQL_USER=fred
     - MYSQL_PASSWORD=fred
  fredbet:
    image: fred4jupiter/fredbet:latest
    depends_on:
      - mariadb
    ports:
      - "8080:8080"
    environment:
     - SPRING_PROFILES_ACTIVE=maria
     - SPRING_DATASOURCE_URL=jdbc:mariadb://mariadb:3306/fredbetdb
     - SPRING_DATASOURCE_USERNAME=fred
     - SPRING_DATASOURCE_PASSWORD=fred
     - SPRING_DATASOURCE_DRIVER_CLASS_NAME=org.mariadb.jdbc.Driver